{
  description = "Fresh NixOS — KDE Plasma 6, impermanent root, full-disk encryption";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # No nixpkgs input to follow — impermanence is a pure module set.
    impermanence.url = "github:nix-community/impermanence";

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    inputs@{
      nixpkgs,
      disko,
      impermanence,
      home-manager,
      ...
    }:
    {
      nixosConfigurations.nixos-machine = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        specialArgs = { inherit inputs; };
        modules = [
          disko.nixosModules.disko
          impermanence.nixosModules.impermanence
          home-manager.nixosModules.home-manager
          ./disko.nix
          ./configuration.nix
          # Regenerated by installer.sh (nixos-generate-config --no-filesystems).
          # The version committed here is correct for this laptop and lets the
          # flake evaluate — and therefore dry-run — before any disk is touched.
          ./hardware-configuration.nix
        ];
      };

      # `disko` reads this BEFORE nixosConfigurations can evaluate (there are no
      # filesystems yet). Same file, no second source of truth.
      diskoConfigurations.default = import ./disko.nix;
    };
}
