# Regenerated by installer.sh with `nixos-generate-config --no-filesystems`.
# --no-filesystems matters: disko owns every fileSystems/swapDevices entry, and
# a second definition from here would collide.
#
# The values below are correct for this laptop (Ryzen 5 8645HS, NVMe, hybrid
# RTX 4050 + Radeon 760M). They exist so the flake evaluates — and so the
# installer's dry-run works — before a single byte is written to any disk.
{ config, lib, modulesPath, ... }:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = true;
}
