{
  pkgs,
  user,
  fullName,
  email,
  ...
}:
let
  # The palette moved to ./palette.nix so flake.nix can assert its contrast figures
  # without evaluating the whole system. Same values, one import away.
  inherit (import ./palette.nix)
    theme
    themeBright
    themeVivid
    backgroundHard
    ;

  # One string, four styles. Change this to reface the terminal.
  terminalFont = "Geist Mono";

  # Codex reads ~/.codex/AGENTS.md the way Claude reads ~/.claude/CLAUDE.md, and
  # the rules are the same rules — so the body here IS claude/CLAUDE.md, byte for
  # byte, rather than a second copy free to drift. Only a header is prepended, and
  # it earns its place by saying which of the walls the body describes actually
  # exist for the agent reading it, and which are thinner than Claude's.
  codexAgentsMd = pkgs.writeText "AGENTS.md" (
    ''
      <!-- Generated by modules/home/default.nix. Editing this is pointless: it
           arrives as a read-only store symlink, and everything below the rule is
           /etc/nixos/claude/CLAUDE.md verbatim. Edit that and rebuild. -->

      # Reading this as Codex

      What follows was written for Claude Code, and is the same set of rules for
      you: the seven laws, the version control model, the shell conventions and the
      shape statement all apply unchanged. Two things do not carry over.

      **The paths.** Where the text says `~/.claude/CLAUDE.md`, you are reading
      `~/.codex/AGENTS.md`. `~/.claude/settings.json` is `~/.codex/config.toml`
      here, `~/.claude/skills/` is `~/.codex/skills/`, and `CLAUDE_CONFIG_DIR` is
      `CODEX_HOME`.

      **The walls.** The section "What is enforced, and what is only written down"
      describes deny rules and hooks generated into
      `/etc/claude-code/managed-settings.json`. You do not read that file — you read
      `/etc/codex/requirements.toml`, and modules/nixos/codex.nix generates it from
      the same guards, so those walls are real for you too. A deny you hit is the
      guard working: read the reason and comply rather than routing around it.

      Two differences are yours alone. **A deny may mean "could not tell".** Claude
      can answer an undecidable payload by asking the user; you cannot, because
      Codex parses `escalate` and `ask`, marks the hook failed, and runs the command
      anyway — so asking would be the same as allowing. Those cases collapse to deny
      instead, and the reason says which it is. If it says the guard could not
      decide, that is a false positive from the collapse, not a rule you broke.

      **And some are thinner than Claude's.** Writing a `*.sh` is NOT shellchecked
      for you: that gate keys on a field Claude's edit tool sets and `apply_patch`
      does not, so run `shellcheck -x` yourself before calling a shell script
      finished. The file rule reads `apply_patch`'s own text, so editing a generated
      file through the SHELL (`sed -i`, `cat >`) is not walled off for you at all —
      Claude has an auto-mode classifier covering that route and you do not. The
      spill rule is best-effort: it keys on a path shape that has not been seen in a
      real Codex payload, so treat it as yours to follow rather than as enforced.
      And nothing runs at session start or session end for you — no convention
      check when you begin, and no reminder that a built configuration is waiting to
      be switched when you stop. Those are Claude's alone. The deny list, the TUI
      rules, the commit gate and the law-1 command shapes all apply in full.

      Follow the rest because they are right, not because something is watching.

      ---

    ''
    + builtins.readFile ../../claude/CLAUDE.md
  );
in
{
  imports = [
    ./plasma.nix
    ./skills.nix
  ];

  home.username = user;
  home.homeDirectory = "/home/${user}";
  home.stateVersion = "26.05";

  programs.fish.enable = true;

  # devenv's workflow is `cd project && <shell loads>`. direnv is the piece that
  # makes that happen; without it every devenv shell is a manual command.
  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
    enableFishIntegration = true;
  };

  programs.git = {
    enable = true;
    settings = {
      user = {
        name = fullName;
        inherit email;
      };
      init.defaultBranch = "main";
      pull.rebase = true;
      # /etc/nixos is root-owned and this user is not root, so libgit2 refuses
      # to open it — which breaks `nh os switch`, since nh declines to run as
      # root. This is the declarative equivalent of `git config --global --add
      # safe.directory`, which cannot be run here: ~/.config/git/config is a
      # read-only store symlink.
      safe.directory = [ "/etc/nixos" ];
      push.autoSetupRemote = true;
      # jj writes its own operations through the git backend; this keeps the
      # colocated .git from re-packing constantly.
      gc.auto = 0;
    };
  };

  # jj does not replace git — it uses git repos as its backend, and `gh` talks
  # git. Both are installed; this just makes jj usable on day one.
  programs.jujutsu = {
    enable = true;
    settings = {
      user = {
        name = fullName;
        inherit email;
      };
      ui = {
        # Bare `jj` shows the log rather than the help text.
        default-command = "log";
        # Set explicitly rather than left to $EDITOR, so `jj describe` does not
        # depend on which shell it was launched from. nvim blocks in place; the
        # GUI window this used to open is what made a forgotten -m hang.
        editor = "nvim";
      };
      # Everything else is left at jj 0.44's defaults on purpose — `git.colocate`
      # and `git.track-default-bookmark-on-clone` are already true, and the
      # `git.auto-local-bookmark` you may have seen in older guides no longer
      # exists (checked against `jj util config-schema`, not from memory).
    };
  };

  # The operation log made visible. jj's model (no staging area, every change is
  # a commit, `jj undo` on anything) clicks far faster when you can see it.
  programs.jjui.enable = true;

  programs.alacritty = {
    enable = true;
    settings = {
      # ── Typography ──────────────────────────────────────────────────────
      # Geist Mono carries no icon glyphs, so those arrive through the
      # fontconfig fallback — JetBrainsMono Nerd Font *Mono*, not plain "Nerd
      # Font": the Mono variant forces icons to single cell width. The
      # proportional variants let them bleed into the next cell and shear the
      # whole grid.
      font = {
        normal = {
          family = terminalFont;
          style = "Regular";
        };
        bold = {
          family = terminalFont;
          style = "Bold";
        };
        italic = {
          family = terminalFont;
          style = "Italic";
        };
        bold_italic = {
          family = terminalFont;
          style = "Bold Italic";
        };
        size = 12.5;
        # +2px of leading. Terminal output is unindented and left-aligned, so
        # the row is the only unit separating one line from the next — a little
        # air makes dense logs scannable without costing a font size.
        offset = {
          x = 0;
          y = 2;
        };
      };

      # ── Frame ───────────────────────────────────────────────────────────
      window = {
        # Asymmetric on purpose: the eye reads the left edge on every single
        # line, so horizontal margin does more work than vertical. Equal padding
        # looks correct in a screenshot and feels cramped in use.
        padding = {
          x = 14;
          y = 10;
        };
        dynamic_padding = true;
        # decorations = "Full" means the compositor draws a titlebar, and the
        # default here is "None", which means "whatever variant the system theme
        # is". A light titlebar above a #1d2021 terminal is the one seam in an
        # otherwise dark window, and it is decided by something outside this file.
        # Pin it, so the frame matches the thing it frames.
        decorations_theme_variant = "Dark";
        # Deliberately opaque. Transparency puts a moving, arbitrary background
        # behind antialiased glyph edges, which is exactly where legibility is
        # decided — and Plasma's blur wakes the dGPU for the compositor.
        opacity = 1.0;
        blur = false;
        decorations = "Full";
        dynamic_title = true;
      };

      cursor = {
        style = {
          shape = "Block";
          # No blink. A blinking cursor is motion in the periphery, and it never
          # stops — it competes for attention with the output you are reading.
          blinking = "Off";
        };
        # Hollow when unfocused, so "which window has my keystrokes" is
        # answerable at a glance across several terminals.
        unfocused_hollow = true;
      };

      # ── Behaviour ───────────────────────────────────────────────────────
      # Alacritty has no tabs and upstream has refused them for years — the
      # answer it gives is "run a multiplexer", and zellij is already installed
      # here for precisely that (tools.json: "the tabs Alacritty deliberately
      # lacks"). Running it *as* the shell is what makes that answer actually
      # load, instead of it depending on remembering to type `zellij` first.
      #
      # Bare, with no `attach`: each window gets its own session, so two windows
      # are independent rather than mirroring one another's panes. `alacritty -e
      # <cmd>` still bypasses this entirely when a raw shell is wanted.
      terminal.shell = {
        program = "${pkgs.zellij}/bin/zellij";
        args = [ ];
      };

      scrolling = {
        history = 50000;
        multiplier = 3;
      };

      selection = {
        save_to_clipboard = true;
        # Default set minus '/' and '-', so double-click grabs a whole path or a
        # kebab-case flag instead of one fragment of it.
        semantic_escape_chars = ",│`|:\"' ()[]{}<>\t";
      };

      mouse.hide_when_typing = true;

      # Visual bell off. duration = 0 disables the flash entirely.
      bell.duration = 0;

      # Setting `hints.enabled` REPLACES Alacritty's built-in URL hint rather than
      # adding to it, so the default is restated verbatim below and the store-path
      # hint sits beside it. Drop the first entry and clicking a link stops working.
      #
      # The second is this machine's own: a /nix/store path is the single string
      # that appears most in a NixOS session and is the least typeable — 32 base32
      # characters nobody will retype correctly. Ctrl+Shift+P labels every one on
      # screen and copies the chosen one. Copy rather than open, because a store
      # path is usually wanted as an argument to the next command, not as a folder.
      # Ctrl+Shift+N is taken by CreateNewWindow below.
      hints.enabled = [
        {
          command = "xdg-open";
          hyperlinks = true;
          post_processing = true;
          persist = false;
          mouse.enabled = true;
          binding = {
            key = "O";
            mods = "Control|Shift";
          };
          regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\\u0000-\\u001F\\u007F-\\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+";
        }
        {
          # /nix/store/<32 base32 chars>-<name>, plus any path inside it.
          regex = "/nix/store/[0-9a-df-np-sv-z]{32}-[^\\s\"'`,;:()\\[\\]{}]+";
          action = "Copy";
          post_processing = false;
          persist = false;
          mouse.enabled = false;
          binding = {
            key = "P";
            mods = "Control|Shift";
          };
        }
      ];

      keyboard.bindings = [
        # Alacritty has no tabs by design, so a new window is the tab. This is
        # the one binding worth adding — CreateNewWindow reuses the running
        # process, unlike SpawnNewInstance which starts a second one.
        {
          key = "N";
          mods = "Control|Shift";
          action = "CreateNewWindow";
        }
      ];

      # ── Colour ──────────────────────────────────────────────────────────
      colors = {
        primary = {
          background = backgroundHard;
          foreground = theme.base05;
          dim_foreground = theme.base04;
          bright_foreground = theme.base07;
        };

        cursor = {
          text = theme.base00;
          cursor = theme.base05;
        };

        # Bright blue, so vi mode is unmistakably a different mode.
        vi_mode_cursor = {
          text = theme.base00;
          cursor = themeBright.base0D;
        };

        # Explicit selection foreground rather than CellForeground: selected
        # text keeping its own colour is unreadable when that colour is dark
        # against base02.
        selection = {
          background = theme.base02;
          text = theme.base07;
        };

        # The two oranges earn their keep here. Search needs "a match" and "the
        # match" to be distinct at a glance, and orange-vs-yellow separates
        # without introducing a colour foreign to the palette.
        search = {
          matches = {
            foreground = theme.base00;
            background = theme.base0A;
          };
          focused_match = {
            foreground = theme.base00;
            background = theme.base09;
          };
        };

        hints = {
          start = {
            foreground = theme.base00;
            background = theme.base0A;
          };
          end = {
            foreground = theme.base00;
            background = theme.base04;
          };
        };

        footer_bar = {
          foreground = theme.base05;
          background = theme.base01;
        };

        # The ANSI normal slots take gruvbox's bright values, not its dark ones.
        # Measured against this background, the dark set fails where it is read
        # most: red 3.00:1, magenta 3.87, blue 3.88, all under the 4.5 needed to
        # read comfortably, and red is what errors and diff removals use. The
        # bright set clears it everywhere, 4.77:1 at worst. Saturation rises with
        # the contrast, which is the same change seen from the other side.
        #
        # white takes base04 rather than base03: 7.53:1 instead of 4.47:1, and
        # the grey ladder stays monotonic, base00 < base02 < base04 < base07.
        normal = {
          black = theme.base00;
          red = themeBright.base08;
          green = themeBright.base0B;
          yellow = themeBright.base0A;
          blue = themeBright.base0D;
          magenta = themeBright.base0E;
          cyan = themeBright.base0C;
          white = theme.base04;
        };

        bright = {
          black = theme.base02;
          red = themeVivid.base08;
          green = themeVivid.base0B;
          yellow = themeVivid.base0A;
          blue = themeVivid.base0D;
          magenta = themeVivid.base0E;
          cyan = themeVivid.base0C;
          white = theme.base07;
        };

        # `dim` is left underived on purpose: gruvbox's faded variants are far
        # too dark on this background, and Alacritty's automatic dimming beats
        # anything hand-picked here.

        # Gruvbox's own convention: the oranges live at 16 and 17, because ANSI
        # has no orange. Anything written for gruvbox reaches for these.
        indexed_colors = [
          {
            index = 16;
            color = theme.base09;
          }
          {
            index = 17;
            color = theme.base0F;
          }
        ];
      };
    };
  };

  # `nix-locate <binary>` answers which package ships a file, without guessing at
  # attribute names — the lookup step that "a missing tool is a decision" asks for.
  # The database comes prebuilt from nix-index-database (see home-manager.nix);
  # nothing indexes anything on this machine.
  # Integration off on purpose. The handler that module emits prints `nix-env
  # -iA nixpkgs.<attr>` — imperative installation, the one thing law 1 forbids.
  # It picks that branch because ~/.nix-profile/manifest.json does not exist on
  # this machine, so the legacy advice is all it can offer. A missing command is
  # the moment you are most likely to run whatever the terminal just suggested,
  # which makes wrong advice there more expensive than no advice at all.
  programs.nix-index = {
    enable = true;
    enableFishIntegration = false;
  };

  # The replacement: same nix-locate lookup, same trigger, routed by law 1
  # instead. fish 4 calls fish_command_not_found directly — the module's
  # deprecated `--on-event` form is the other reason the integration above is
  # off, since both would fire and print twice.
  #
  # home-manager wraps interactiveShellInit in `status is-interactive`, so this
  # never loads in an agent or script shell. That matters: the nix-index script
  # bails to a bare message when stdout is not a TTY, and this keeps that shape.
  programs.fish.interactiveShellInit = ''
    function fish_command_not_found
        set -l cmd $argv[1]
        if not command -q nix-locate
            echo "$cmd: command not found" >&2
            return 127
        end
        set -l attrs (nix-locate --minimal --no-group --type x --type s \
            --whole-name --at-root "/bin/$cmd" | string replace -r "\.out\$" "" | head -5)
        if test (count $attrs) -eq 0
            echo "$cmd: command not found, and no nixpkgs package ships it" >&2
            return 127
        end
        echo "$cmd is not installed. Law 2: that is a decision, so pick one." >&2
        echo >&2
        echo "  once, leaving nothing behind:" >&2
        for a in $attrs
            echo "      nix shell nixpkgs#$a -c $cmd ..." >&2
        end
        echo "      , $cmd ...                    same lookup, fetches and runs" >&2
        echo >&2
        echo "  declared, so it survives a reboot:" >&2
        echo "      devenv.nix                    this project only" >&2
        echo "      modules/nixos/packages.nix    this machine, system-wide" >&2
        echo "      modules/home/default.nix      this machine, your user" >&2
        return 127
    end
  '';

  # LazyVim, split the way the VS Code extensions above are split: the config is
  # declared, the plugin churn is not.
  #
  # lua/config and lua/plugins are symlinked as whole directories, so a new file
  # dropped into either is picked up without a second declaration to remember —
  # and ~/.config/nvim itself stays a real, writable directory. That last part is
  # load-bearing: lazy.nvim writes lazy-lock.json into the config root, which a
  # store symlink would make impossible.
  #
  # The plugins themselves clone into ~/.local/share/nvim/lazy at first launch.
  # That is state, and impermanence.nix persists .local/share, so it survives a
  # reboot without being declared. The cost, stated plainly: lazy-lock.json is
  # writable rather than declared, so a *fresh* machine resolves plugins at
  # whatever is current instead of what this one pinned. Copy the lockfile into
  # nvim/ and add a line here if that day matters more than `:Lazy update` does.
  xdg.configFile = {
    "nvim/init.lua".source = ../../nvim/init.lua;
    "nvim/stylua.toml".source = ../../nvim/stylua.toml;
    "nvim/lua/config".source = ../../nvim/lua/config;
    "nvim/lua/plugins".source = ../../nvim/lua/plugins;

    # zellij wrote its own 20 KB default dump here on first run — undeclared
    # state for a program that is the shell of every terminal window. This
    # replaces it with the keybinding decision, which is a rule and belongs in
    # the repo. Not merged into a `programs.zellij` module because zellij stays
    # in packages.nix and adding the module would install a second copy.
    "zellij/config.kdl".source = ../../zellij/config.kdl;

    # herdr, for the same reason as zellij directly above — and it had not
    # written its config yet when this landed, so nothing had to be moved aside.
    # The file holds the theme and the onboarding answer and nothing else;
    # /etc/nixos/herdr/config.toml says why each is there.
    #
    # The cost, stated plainly: `herdr config reset-keys` cannot work against a
    # read-only symlink. It exists to undo hand-edited keybindings, and there are
    # none to undo when the file is declared, so the command is answering a
    # question this setup does not raise.
    "herdr/config.toml".source = ../../herdr/config.toml;
  };

  # gcc, gnumake, nodejs and unzip are all in tools.json's not_installed list,
  # and this does not contradict that. The reason each is absent is that a system
  # copy shadows a project's pinned toolchain; extraPackages is `--suffix PATH` on
  # neovim's own wrapper (home-manager neovim/default.nix:508), so these exist for
  # nvim's subprocesses and nowhere else. A devenv shell still wins in a terminal.
  #
  # What needs them: nvim-treesitter compiles parsers with a C compiler, and
  # mason.nvim unpacks and runs LSP servers, many of them npm packages. Mason's
  # prebuilt binaries run at all here because programs.nix-ld.enable is true.
  #
  # No lazygit, though LazyVim binds <leader>gg to it: local history here is jj,
  # and a git TUI pointed at a colocated repo is a worse answer than no answer.
  programs.neovim = {
    enable = true;
    viAlias = true;
    vimAlias = true;
    extraPackages = with pkgs; [
      gcc
      gnumake
      nodejs
      unzip
      tree-sitter
    ];
  };

  # `ls` was still coreutils. eza sat in packages.nix for eleven days with no
  # alias, so nothing ever reached for it — the same failure zellij had, and it
  # is visible in this machine's own history: `ls` 599 times, `eza` zero. The
  # fish integration is the whole fix, because it puts the tool inside a habit
  # that already exists rather than asking for a new one (ls/ll/la/lt/lla).
  #
  # Declared here rather than in packages.nix because it is a user tool and the
  # aliases are a user-shell concern; the aliases are mkDefault and land only in
  # interactive fish, so agent shells and scripts still get coreutils `ls` and
  # its parseable output.
  #
  # icons is not decoration here — modules/nixos/fonts.nix installs a Nerd Font
  # and its comment names `eza --icons` as the reason. Until now that was
  # aspirational: the font was there for a flag nothing passed.
  programs.eza = {
    enable = true;
    enableFishIntegration = true;
    icons = "auto";
    git = true;
  };
  programs.fzf = {
    enable = true;
    enableFishIntegration = true;
  };

  home.sessionVariables = {
    # nvim, since VS Code is gone. It blocks in the terminal it was invoked
    # from, so a forgotten `jj describe` -m waits rather than opening a window
    # a headless session cannot see — and agent sessions still pin this to
    # `false` through managed settings, which is the guard that actually holds.
    EDITOR = "nvim";
    # Relocates .claude.json into ~/.claude, which is a persisted directory
    # (modules/nixos/impermanence.nix). Left unset, it lives loose in the home root
    # and does not survive a reboot. Verified against claude-code 2.1.228:
    # with this set, the json is created inside the directory, not beside it.
    CLAUDE_CONFIG_DIR = "/home/${user}/.claude";
  };

  # Claude Code's instructions and the check that keeps them honest are rules, so
  # they are declared here and reach ~/.claude as store symlinks — a fresh machine
  # built from this repo gets them, and editing the copy is impossible rather than
  # merely discouraged. Everything else under ~/.claude is *state* (settings.json's
  # theme, .claude.json, projects/, credentials) and stays writable and undeclared;
  # it survives reboots via the persisted path in modules/nixos/impermanence.nix.
  #
  # The rules half of settings.json — the editor guard and the nh hook — cannot live
  # here, because Claude Code must be able to write that file. It is declared as
  # managed settings instead; see modules/nixos/claude.nix.
  home.file = {
    ".claude/CLAUDE.md".source = ../../claude/CLAUDE.md;
    ".codex/AGENTS.md".source = codexAgentsMd;
    ".claude/check-conventions.sh" = {
      source = ../../claude/check-conventions.sh;
      executable = true;
    };
    # No skills are declared. `unslop` (vendored from cursor/plugins) was the only
    # one and was dropped 2026-08-22: its own description claimed it must always
    # apply, so its ~6.6 KB body loaded on essentially every session that wrote
    # prose, which is a standing cost for a style guide. The split it illustrated
    # still holds — a global skill belongs here, a project one in that project's
    # own repo — and check-conventions.sh keeps asserting that nothing under
    # ~/.claude/skills is hand-written, so the rule outlives the example.
  };
}
