# The deny list, shared by every agent this machine runs.
#
# Claude consumes it declaratively — `permissions.deny` takes these patterns as
# they are. Codex has no declarative deny mechanism at all, so codex.nix turns the
# same patterns into a hook. That asymmetry is the whole reason this file exists:
# the list was Claude's alone until 2026-08-24, and the port found that 16 of the
# 20 rules had silently not made it across while Codex's own instructions claimed
# they had. One list, two consumers, so that cannot recur.
#
# Each group carries the reason as DATA rather than as a comment, because Codex's
# hook has to say something when it denies. Claude's deny needs no string — it
# reports the pattern — which is why these read as prose rather than as labels.
{
  lib,
  agentUnsafe,
}:
rec {
  # hosts/*/hardware-configuration.nix is generated by nixos-generate-config, and
  # tools.json has said "never hand-edited" all along — but prose does not stop
  # tooling: a `deadnix --edit` pass stripped an unused argument from it twice
  # within ten minutes (2026-08). default.nix and disko.nix beside it are
  # hand-written and must stay editable, hence the exact filename rather than the
  # directory.
  #
  # For Claude one pattern is the whole wall: `Edit(path)` is THE file rule and
  # governs Edit, Write, MultiEdit and NotebookEdit together. Codex has no file
  # rule, so `codexMatch` is a substring test against apply_patch's command —
  # broader than the path glob on purpose, because that filename exists nowhere
  # else on this machine and a false positive costs one refused edit.
  fileRule = {
    pattern = "//etc/nixos/hosts/*/hardware-configuration.nix";
    codexMatch = "*hardware-configuration.nix*";
    reason = "hosts/*/hardware-configuration.nix is generated by nixos-generate-config and is never hand-edited — a `deadnix --edit` pass stripped an argument out of it twice within ten minutes. Change the hardware by re-running the generator, not by editing the file. default.nix and disko.nix beside it are hand-written and stay editable.";
  };

  # Everything the inventory marks interactive. Four rules today; the list is
  # whatever tools.json says it is.
  tuiDenies = map (c: "Bash(${c} *)") (lib.naturalSort agentUnsafe);

  bashGroups = [
    {
      # `fd -x/-X` runs arbitrary commands and is idiomatic enough to type by
      # accident; `nix eval --write-to` writes a directory. Both tools are
      # allow-listed for Claude and deny beats allow, so the pair composes. Two
      # position variants each, because a trailing ` *` will not match a flag
      # sitting immediately after the command name.
      reason = "`fd -x/-X/--exec` runs an arbitrary command per result, and `nix eval --write-to` writes a directory — both are easy to reach by accident from a tool that is otherwise safe. Run the command yourself over the results instead.";
      patterns = [
        "fd -x *"
        "fd -X *"
        "fd --exec*"
        "fd * -x *"
        "fd * -X *"
        "fd * --exec*"
        "nix eval --write-to*"
        "nix eval * --write-to*"
      ];
    }
    {
      # jj's DIFF editor, which the env guard does not reach. Bare `jj split` and
      # bare `jj resolve` open it; `jj split <paths>` and `jj resolve --list` are
      # non-interactive and stay available, hence the exact-match form for those
      # two.
      reason = "this opens jj's builtin diff editor, which is a TUI: a session with no terminal cannot drive it, so it hangs rather than fails (law 3). The non-interactive forms stay available — `jj split <paths>` takes filesets, `jj resolve --list` lists conflicts, and a conflict is resolved by editing the marked files directly and then `jj squash`.";
      patterns = [
        "jj split"
        "jj resolve"
        "jj diffedit *"
        "jj * -i *"
        "jj * --interactive *"
      ];
    }
    {
      reason = "`sg` here is util-linux's setgid wrapper, not ast-grep. It exists, it runs, and it does something entirely different — the worst shape a typo can have. The tool you want is `ast-grep`, by that name.";
      patterns = [ "sg *" ];
    }
    {
      reason = "this reaches a sudo prompt no agent session can answer (law 3). Take the work to a clean `nh os build` and hand the switch over — denying it here turns a confusing `sudo: a terminal is required` after a full build into an immediate hand-off.";
      patterns = [ "nh os switch *" ];
    }
  ];

  # Claude's form. Order is load-bearing only in that it must not change without
  # a reason: the generated managed-settings.json is compared byte-for-byte
  # across refactors of this file.
  claudeDeny = [
    "Edit(${fileRule.pattern})"
  ]
  ++ tuiDenies
  ++ lib.concatMap (g: map (p: "Bash(${p})") g.patterns) bashGroups;
}
