# The deny list, shared by every agent this machine runs.
#
# Claude consumes it declaratively — `permissions.deny` takes these patterns as
# they are. Codex has no declarative deny mechanism at all, so codex.nix turns the
# same patterns into a hook. That asymmetry is the whole reason this file exists:
# the list was Claude's alone until 2026-08-24, and the port found that 16 of the
# 20 rules had silently not made it across while Codex's own instructions claimed
# they had. One list, two consumers, so that cannot recur.
#
# Each group carries the reason as DATA rather than as a comment, because Codex's
# hook has to say something when it denies. Claude's deny needs no string — it
# reports the pattern — which is why these read as prose rather than as labels.
{
  lib,
  agentUnsafe,
}:
rec {
  # hosts/*/hardware-configuration.nix is generated by nixos-generate-config, and
  # tools.json has said "never hand-edited" all along — but prose does not stop
  # tooling: a `deadnix --edit` pass stripped an unused argument from it twice
  # within ten minutes (2026-08). default.nix and disko.nix beside it are
  # hand-written and must stay editable, hence the exact filename rather than the
  # directory.
  #
  # For Claude one pattern is the whole wall: `Edit(path)` is THE file rule and
  # governs Edit, Write, MultiEdit and NotebookEdit together. Verified 2026-08-24
  # against claude-code 2.1.234 — file permissions are checked against `Edit(path)`
  # and `Read(path)` only. So do NOT add a `Write(...)` rule beside it to close a
  # gap: there is none, and such a rule is accepted, never consulted, and warned
  # about at startup — a lock whose only effect is to look like a second one.
  #
  # Codex has no file rule at all, so `codexMatch` is a substring test against
  # apply_patch's command — broader than the path glob on purpose, because that
  # filename exists nowhere else here and a false positive costs one refused edit.
  fileRule = {
    pattern = "//etc/nixos/hosts/*/hardware-configuration.nix";
    codexMatch = "*hardware-configuration.nix*";
    reason = "hosts/*/hardware-configuration.nix is generated by nixos-generate-config and is never hand-edited — a `deadnix --edit` pass stripped an argument out of it twice within ten minutes. Change the hardware by re-running the generator, not by editing the file. default.nix and disko.nix beside it are hand-written and stay editable.";
  };
  # Everything the inventory marks interactive. The list is whatever tools.json
  # says it is, and no count is written here — a count is a second copy of a fact,
  # and this one was already wrong.
  #
  # Each entry says WHICH forms hang, because the two cases are genuinely
  # different and one pattern cannot express both:
  #
  #   forms = "all"   the whole command is a TUI. `nvim`, `fzf` and `jjui`.
  #                   Both patterns, for the same reason the jj
  #                   group carries both — `btop *` does not match a bare `btop`,
  #                   which is the form actually typed. Claude ran with only the
  #                   ` *` variant until 2026-08-24.
  #
  #   forms = "bare"  the word alone is a TUI and its subcommands are scriptable.
  #                   `codex` hangs, `codex exec` does not. Emitting `codex *`
  #                   here would deny the useful half and still miss the form
  #                   that hangs — an inversion, not an over-approximation.
  #
  # That second case existed before this field could express it, and the cost was
  # visible: codex's rule was hand-written into bashGroups below while tools.json
  # recorded the tool as safe, so the field said one thing and a note beside it
  # said the opposite. A shape that cannot state a true fact does not prevent the
  # fact — it relocates it somewhere nothing derives from.
  byForm = f: lib.sort (a: b: a.command < b.command) (builtins.filter (e: e.forms == f) agentUnsafe);

  barePatterns = map (e: e.command) (byForm "bare");
  allPatterns = lib.concatMap (e: [
    e.command
    "${e.command} *"
  ]) (byForm "all");

  # `nix run <flake>#<attr>` is the same hang with no `-c` in it. It runs the
  # package's default app directly, so the wrapped-command unwrap in
  # agent-guards.nix has nothing to extract and the segment's own first word is
  # `nix` — `nix run nixpkgs#neovim` passed every wall here while `nix shell
  # nixpkgs#neovim -c nvim` was refused. There is no textual route from the attr
  # to the binary either (`neovim` starts `nvim`), which makes this the one rule
  # that must be keyed on the PACKAGE rather than on the command — and tools.json
  # is where that mapping already lives, so the key comes from the same entry as
  # everything else here rather than from a second list.
  #
  # Split by form for the same reason the patterns above are: for an "all" entry
  # every spelling hangs, and for a "bare" one only the argument-less form does,
  # since `nix run nixpkgs#codex -- exec …` still reaches the scriptable half.
  # A null package is dropped rather than interpolated: those are the base-system
  # entries, which have no attr to `nix run` in the first place.
  #
  # Scoped to the inventory's own spellings, like every other pattern here:
  # `nix run nixpkgs#vim` starts a vim this machine does not declare, and stays
  # out of scope until something declares it.
  #
  # Only entries whose command is the tool's PRIMARY binary — the one `nix run
  # <flake>#<pkg>` actually starts. Two ways that is not the denied command, and
  # this repo now has both:
  #
  #   a subcommand   `mlr repl` and `ast-grep lsp` hang, but `nix run
  #                  nixpkgs#miller` is `mlr` printing its help.
  #   a second binary  scc ships `badges` (an HTTP server) and universal-ctags
  #                  ships `optscript` (a REPL), while `nix run nixpkgs#scc` is
  #                  the line counter and `#universal-ctags` is ctags.
  #
  # A package-level pattern for either denies the whole tool over the flaw of
  # one of its parts. The first version of this test asked only whether the
  # command was one word, which handled the subcommands and would have denied
  # scc and universal-ctags outright — and, because ast-grep declares one entry
  # of each form, it also emitted the same pattern twice, which shellcheck
  # rejects (SC2221) once the arms become a `case`.
  isPrimary = e: e.command == (e.primary or e.command);
  packagesOf =
    f:
    lib.unique (
      builtins.filter (p: p != null) (map (e: e.package or null) (builtins.filter isPrimary (byForm f)))
    );
  nixRunAll = packagesOf "all";
  nixRunBare = builtins.filter (p: !(builtins.elem p nixRunAll)) (packagesOf "bare");
  nixRunPatterns =
    lib.concatMap (p: [
      "nix run *#${p}"
      "nix run *#${p} *"
    ]) nixRunAll
    ++ map (p: "nix run *#${p}") nixRunBare;

  tuiPatterns = barePatterns ++ allPatterns ++ nixRunPatterns;
  tuiDenies = map (p: "Bash(${p})") tuiPatterns;

  # The same patterns as groups, for an agent that has no declarative deny and
  # must run them through a hook instead. Two groups rather than one, because the
  # reason differs with the form: for "all" there is nothing scriptable to point
  # at, and for "bare" naming the subcommands that still work is the difference
  # between a wall and a dead end. An empty group is dropped, so a machine with
  # nothing marked bare emits exactly the one group it used to.
  tuiGroups =
    lib.optional (allPatterns != [ ]) {
      reason = "this is an interactive TUI, and a session with no terminal cannot drive it — it will hang rather than fail (law 2 and law 3). tools.json lists it under agent_unsafe, which is where both agents get this rule from; its purpose note there names the scriptable form where one exists.";
      patterns = allPatterns;
    }
    ++ lib.optional (barePatterns != [ ]) {
      reason = "the bare command opens an interactive TUI and a session with no terminal cannot drive it — it hangs rather than fails (law 3). Only the bare form is denied: this tool's subcommands are non-interactive and stay available, and tools.json's purpose note names them.";
      patterns = barePatterns;
    }
    ++ lib.optional (nixRunPatterns != [ ]) {
      reason = "`nix run <flake>#<attr>` runs that package's default app, and tools.json marks this one interactive: a session with no terminal cannot drive it, so it hangs rather than fails (law 3). It needs no `-c`, which is why no wrapper unwrap catches it and why this rule is keyed on the package attr rather than on the command it starts. Law 1's one-off idiom is untouched in its other spelling — `nix shell nixpkgs#<pkg> -c <command>` — for anything non-interactive.";
      patterns = nixRunPatterns;
    };

  bashGroups = [
    {
      # `fd -x/-X` runs arbitrary commands and is idiomatic enough to type by
      # accident; `nix eval --write-to` writes a directory. Both tools are
      # allow-listed for Claude and deny beats allow, so the pair composes. Two
      # position variants each, because a trailing ` *` will not match a flag
      # sitting immediately after the command name.
      reason = "`fd -x/-X/--exec` runs an arbitrary command per result, and `nix eval --write-to` writes a directory — both are easy to reach by accident from a tool that is otherwise safe. Run the command yourself over the results instead.";
      patterns = [
        "fd -x *"
        "fd -X *"
        "fd --exec*"
        "fd * -x *"
        "fd * -X *"
        "fd * --exec*"
        "nix eval --write-to*"
        "nix eval * --write-to*"
      ];
    }
    {
      # jj's DIFF editor, which the env guard does not reach. Bare `jj split` and
      # `jj resolve` (with or without paths, unless --list or a non-interactive
      # --tool) open it; `jj split <paths>`, `jj resolve --list` and
      # `jj resolve --tool mergiraf` stay available, hence the exact-match form
      # for split/resolve. The pattern language cannot deny `jj resolve <path>`
      # without also denying --list and --tool; an argv-parsing guard slice could
      # (agent-guards.nix has the precedent) — add it if the prose warning in the
      # reason ever fails to hold.
      reason = "this opens jj's builtin diff editor, which is a TUI: a session with no terminal cannot drive it, so it hangs rather than fails (law 3). So does `jj resolve <path>` without a tool, even though no wall catches that spelling. The forms that stay available: `jj split <paths>`, `jj resolve --list`, and `nix shell nixpkgs#mergiraf -c jj resolve --tool mergiraf` — run that first, edit what it leaves marked, and trust its warning output plus `jj log -r 'conflicts()'`, never the exit code.";
      # Every pattern here exists in two forms, argument-full and bare, because a
      # trailing ` *` does NOT match the argument-less command: `Bash(jj diffedit *)`
      # let bare `jj diffedit` straight through, and `jj * -i *` let `jj squash -i`
      # through, for both agents, from the day these were written until 2026-08-24.
      # Both of those open the diff editor and hang a session with no terminal,
      # which is the exact outcome this group exists to prevent.
      patterns = [
        "jj split"
        "jj resolve"
        "jj diffedit"
        "jj diffedit *"
        "jj * -i"
        "jj * -i *"
        "jj * --interactive"
        "jj * --interactive *"
      ];
    }
    {
      reason = "`sg` here is util-linux's setgid wrapper, not ast-grep. It exists, it runs, and it does something entirely different — the worst shape a typo can have. The tool you want is `ast-grep`, by that name.";
      patterns = [
        "sg"
        "sg *"
      ];
    }
    {
      # ast-grep's interactive edit session, which agent_unsafe cannot express:
      # that field keys on a COMMAND, and this hangs on a flag. Same shape as the
      # jj group above and for the same reason — both position variants of both
      # spellings, because `ast-grep -i` (run is the default subcommand) and
      # `ast-grep run -i` are both real, and a trailing ` *` matches neither the
      # flag sitting last nor the flag sitting first.
      #
      # `ast-grep lsp` and bare `ast-grep new` hang too and are NOT here: those
      # are commands, so tools.json says so through agent_unsafe and both agents
      # get them from the inventory.
      reason = "`ast-grep -i/--interactive` opens an interactive edit session, which a session with no terminal cannot drive — it hangs rather than fails (law 3). To see the matches first, run it with `--json` and read them; to apply every match without a session, `-U`/`--update-all`. Rewrites only happen inside one of those two.";
      patterns = [
        "ast-grep -i"
        "ast-grep -i *"
        "ast-grep --interactive"
        "ast-grep --interactive *"
        "ast-grep * -i"
        "ast-grep * -i *"
        "ast-grep * --interactive"
        "ast-grep * --interactive *"
      ];
    }
    {
      reason = "this reaches a sudo prompt no agent session can answer (law 3). Take the work to a clean `nh os build` and hand the switch over — denying it here turns a confusing `sudo: a terminal is required` after a full build into an immediate hand-off.";
      patterns = [
        "nh os switch"
        "nh os switch *"
      ];
    }
    {
      # The docker group is root-equivalent — `docker run -v /:/x` edits the
      # host as root — and unlike wheel it asks for no password, so it stands
      # beside the sudo wall as an open gate: every other rule here assumes
      # that changing the system waits on a prompt only the user can answer.
      # winboat.nix is why the group exists at all, and tools.json already says
      # docker is "not an invitation"; this is that sentence with teeth. Both
      # forms, because even the read-only subcommands have no agent use here —
      # nothing agent-facing runs in a container on this machine.
      #
      # docker-compose is a separate binary from docker itself — "docker-compose
      # up" contains no space after "docker", so neither pattern above ever
      # matched it — and it drives the exact same root-equivalent daemon
      # winboat.nix wires a password-less socket to. Present in nixpkgs
      # (nix-locate confirms), so `nix shell nixpkgs#docker-compose -c
      # docker-compose up` reaches it with no wrapper needed and without
      # winboat's own PATH suffix.
      #
      # podman moved to its own group below. It used to sit in this one under
      # this reason, which was false for it: rootless podman is not in the docker
      # group and is not root-equivalent. A wall whose stated reason does not
      # hold is a wall that gets argued with.
      reason = "the docker group is root-equivalent, and unlike sudo it prompts for nothing — a container with a bind mount edits the host as root, which walks around the password hand-off every other wall here assumes (law 3). Docker exists on this machine for winboat alone (tools.json), not as an agent tool. If a task genuinely needs a container, say so and the user can run it.";
      patterns = [
        "docker"
        "docker *"
        "docker-compose"
        "docker-compose *"
      ];
    }
    {
      # Split out of the docker group 2026-08-30, and widened at the same time.
      # The old arrangement denied `podman-compose` while leaving bare `podman`
      # open — the wrapper refused and the thing it drives allowed — and it did
      # that under a reason about the docker daemon that only holds when podman
      # is pointed at that socket through DOCKER_HOST. Checked: `command -v
      # podman podman-compose` finds neither (tools.json lists podman under
      # not_installed), and DOCKER_HOST appears nowhere in this repo.
      #
      # So the honest version is a separate reason and no asymmetry. Both
      # binaries, both forms.
      reason = "podman is not installed here (tools.json, not_installed), so reaching it means fetching it — and both ends of that are already walled. Pointed at the docker socket with DOCKER_HOST it IS the root-equivalent daemon denied above; rootless it is a container runtime nothing on this machine runs, and law 1 is clear that a container is not the route around a package nixpkgs already has. Rootless podman is genuinely not root-equivalent, which is why this is its own rule rather than the docker one. If a task truly needs a container, say so and the user can run it.";
      patterns = [
        "podman"
        "podman *"
        "podman-compose"
        "podman-compose *"
      ];
    }
  ];

  # The literal prefix of every deny pattern: what a command must CONTAIN before
  # any of these rules could possibly apply to it. Derived from the patterns
  # rather than hand-listed, so a new deny cannot be added without the things
  # that gate on it learning about it.
  #
  # Two consumers, which is why it lives here and not in either of them.
  # codex.nix's denyGuard declares it as the guard's offTrigger, and
  # agent-guards.nix's commandShapeGuard folds it into the literal prefilter that
  # decides whether that guard parses the payload at all. The second one is what
  # closed the wrapper leaks: `timeout 60 nvim`, `FOO=1 nvim` and `, nvim` all
  # unwrap to a denied verb, but the guard used to exit before looking, because
  # none of them contains `nix shell`, `bash -c` or any other literal on the old
  # hand-written list. Judging by the deny list itself is the only version of
  # that list that cannot fall behind it.
  #
  # Deliberately conservative: `jj * -i` reduces to "jj", so every jj command is
  # worth judging, and `sg` matches any command with "sg" anywhere in it. Both
  # over-approximate, which costs a segments pass on commands that turn out fine
  # and never costs a decision — every arm downstream is segment-anchored.
  denyPrefixes = lib.unique (
    lib.filter (s: s != "") (
      map (p: lib.removeSuffix " " (lib.head (lib.splitString "*" p))) (
        lib.concatMap (g: g.patterns) (bashGroups ++ tuiGroups)
      )
    )
  );

  # Claude's form. Order is load-bearing only in that it must not change without
  # a reason: the generated managed-settings.json is compared byte-for-byte
  # across refactors of this file.
  claudeDeny = [
    "Edit(${fileRule.pattern})"
  ]
  ++ tuiDenies
  ++ lib.concatMap (g: map (p: "Bash(${p})") g.patterns) bashGroups;
}
