# The deny list, shared by every agent this machine runs.
#
# Claude consumes it declaratively — `permissions.deny` takes these patterns as
# they are. Codex has no declarative deny mechanism at all, so codex.nix turns the
# same patterns into a hook. That asymmetry is the whole reason this file exists:
# the list was Claude's alone until 2026-08-24, and the port found that 16 of the
# 20 rules had silently not made it across while Codex's own instructions claimed
# they had. One list, two consumers, so that cannot recur.
#
# Each group carries the reason as DATA rather than as a comment, because Codex's
# hook has to say something when it denies. Claude's deny needs no string — it
# reports the pattern — which is why these read as prose rather than as labels.
{
  lib,
  agentUnsafe,
}:
rec {
  # hosts/*/hardware-configuration.nix is generated by nixos-generate-config, and
  # tools.json has said "never hand-edited" all along — but prose does not stop
  # tooling: a `deadnix --edit` pass stripped an unused argument from it twice
  # within ten minutes (2026-08). default.nix and disko.nix beside it are
  # hand-written and must stay editable, hence the exact filename rather than the
  # directory.
  #
  # For Claude one pattern is the whole wall: `Edit(path)` is THE file rule and
  # governs Edit, Write, MultiEdit and NotebookEdit together. Verified 2026-08-24
  # against claude-code 2.1.234 — file permissions are checked against `Edit(path)`
  # and `Read(path)` only. So do NOT add a `Write(...)` rule beside it to close a
  # gap: there is none, and such a rule is accepted, never consulted, and warned
  # about at startup — a lock whose only effect is to look like a second one.
  #
  # Codex has no file rule at all, so `codexMatch` is a substring test against
  # apply_patch's command — broader than the path glob on purpose, because that
  # filename exists nowhere else here and a false positive costs one refused edit.
  fileRule = {
    pattern = "//etc/nixos/hosts/*/hardware-configuration.nix";
    codexMatch = "*hardware-configuration.nix*";
    reason = "hosts/*/hardware-configuration.nix is generated by nixos-generate-config and is never hand-edited — a `deadnix --edit` pass stripped an argument out of it twice within ten minutes. Change the hardware by re-running the generator, not by editing the file. default.nix and disko.nix beside it are hand-written and stay editable.";
  };
  # Everything the inventory marks interactive. The list is whatever tools.json
  # says it is, and no count is written here — a count is a second copy of a fact,
  # and this one was already wrong.
  #
  # Each entry says WHICH forms hang, because the two cases are genuinely
  # different and one pattern cannot express both:
  #
  #   forms = "all"   the whole command is a TUI. `nvim`, `fzf`, `jjui`, and
  #                   `zellij attach`. Both patterns, for the same reason the jj
  #                   group carries both — `btop *` does not match a bare `btop`,
  #                   which is the form actually typed. Claude ran with only the
  #                   ` *` variant until 2026-08-24.
  #
  #   forms = "bare"  the word alone is a TUI and its subcommands are scriptable.
  #                   `codex` hangs, `codex exec` does not. Emitting `codex *`
  #                   here would deny the useful half and still miss the form
  #                   that hangs — an inversion, not an over-approximation.
  #
  # That second case existed before this field could express it, and the cost was
  # visible: codex's rule was hand-written into bashGroups below while tools.json
  # recorded the tool as safe, so the field said one thing and a note beside it
  # said the opposite. A shape that cannot state a true fact does not prevent the
  # fact — it relocates it somewhere nothing derives from.
  byForm = f: lib.sort (a: b: a.command < b.command) (builtins.filter (e: e.forms == f) agentUnsafe);

  barePatterns = map (e: e.command) (byForm "bare");
  allPatterns = lib.concatMap (e: [
    e.command
    "${e.command} *"
  ]) (byForm "all");

  tuiPatterns = barePatterns ++ allPatterns;
  tuiDenies = map (p: "Bash(${p})") tuiPatterns;

  # The same patterns as groups, for an agent that has no declarative deny and
  # must run them through a hook instead. Two groups rather than one, because the
  # reason differs with the form: for "all" there is nothing scriptable to point
  # at, and for "bare" naming the subcommands that still work is the difference
  # between a wall and a dead end. An empty group is dropped, so a machine with
  # nothing marked bare emits exactly the one group it used to.
  tuiGroups =
    lib.optional (allPatterns != [ ]) {
      reason = "this is an interactive TUI, and a session with no terminal cannot drive it — it will hang rather than fail (law 2 and law 3). tools.json lists it under agent_unsafe, which is where both agents get this rule from; its purpose note there names the scriptable form where one exists.";
      patterns = allPatterns;
    }
    ++ lib.optional (barePatterns != [ ]) {
      reason = "the bare command opens an interactive TUI and a session with no terminal cannot drive it — it hangs rather than fails (law 3). Only the bare form is denied: this tool's subcommands are non-interactive and stay available, and tools.json's purpose note names them.";
      patterns = barePatterns;
    };

  bashGroups = [
    {
      # `fd -x/-X` runs arbitrary commands and is idiomatic enough to type by
      # accident; `nix eval --write-to` writes a directory. Both tools are
      # allow-listed for Claude and deny beats allow, so the pair composes. Two
      # position variants each, because a trailing ` *` will not match a flag
      # sitting immediately after the command name.
      reason = "`fd -x/-X/--exec` runs an arbitrary command per result, and `nix eval --write-to` writes a directory — both are easy to reach by accident from a tool that is otherwise safe. Run the command yourself over the results instead.";
      patterns = [
        "fd -x *"
        "fd -X *"
        "fd --exec*"
        "fd * -x *"
        "fd * -X *"
        "fd * --exec*"
        "nix eval --write-to*"
        "nix eval * --write-to*"
      ];
    }
    {
      # jj's DIFF editor, which the env guard does not reach. Bare `jj split` and
      # bare `jj resolve` open it; `jj split <paths>`, `jj resolve --list` and
      # `jj resolve --tool <tool>` are non-interactive and stay available, hence
      # the exact-match form for split/resolve. `jj resolve <path>` without
      # `--tool` also opens the TUI, but a pattern catching it would take --list
      # and --tool down with it, so that slice stays prose in CLAUDE.md.
      reason = "this opens jj's builtin diff editor, which is a TUI: a session with no terminal cannot drive it, so it hangs rather than fails (law 3). The non-interactive forms stay available — `jj split <paths>` takes filesets, `jj resolve --list` lists conflicts, and `jj resolve --tool mergiraf` auto-merges what it can; edit the files it leaves marked directly, and trust `jj resolve --list`, not the exit code, to say whether any remain.";
      # Every pattern here exists in two forms, argument-full and bare, because a
      # trailing ` *` does NOT match the argument-less command: `Bash(jj diffedit *)`
      # let bare `jj diffedit` straight through, and `jj * -i *` let `jj squash -i`
      # through, for both agents, from the day these were written until 2026-08-24.
      # Both of those open the diff editor and hang a session with no terminal,
      # which is the exact outcome this group exists to prevent.
      patterns = [
        "jj split"
        "jj resolve"
        "jj diffedit"
        "jj diffedit *"
        "jj * -i"
        "jj * -i *"
        "jj * --interactive"
        "jj * --interactive *"
      ];
    }
    {
      reason = "`sg` here is util-linux's setgid wrapper, not ast-grep. It exists, it runs, and it does something entirely different — the worst shape a typo can have. The tool you want is `ast-grep`, by that name.";
      patterns = [
        "sg"
        "sg *"
      ];
    }
    {
      reason = "this reaches a sudo prompt no agent session can answer (law 3). Take the work to a clean `nh os build` and hand the switch over — denying it here turns a confusing `sudo: a terminal is required` after a full build into an immediate hand-off.";
      patterns = [
        "nh os switch"
        "nh os switch *"
      ];
    }
    {
      # The docker group is root-equivalent — `docker run -v /:/x` edits the
      # host as root — and unlike wheel it asks for no password, so it stands
      # beside the sudo wall as an open gate: every other rule here assumes
      # that changing the system waits on a prompt only the user can answer.
      # winboat.nix is why the group exists at all, and tools.json already says
      # docker is "not an invitation"; this is that sentence with teeth. Both
      # forms, because even the read-only subcommands have no agent use here —
      # nothing agent-facing runs in a container on this machine.
      reason = "the docker group is root-equivalent, and unlike sudo it prompts for nothing — a container with a bind mount edits the host as root, which walks around the password hand-off every other wall here assumes (law 3). Docker exists on this machine for winboat alone (tools.json), not as an agent tool. If a task genuinely needs a container, say so and the user can run it.";
      patterns = [
        "docker"
        "docker *"
      ];
    }
  ];

  # Claude's form. Order is load-bearing only in that it must not change without
  # a reason: the generated managed-settings.json is compared byte-for-byte
  # across refactors of this file.
  claudeDeny = [
    "Edit(${fileRule.pattern})"
  ]
  ++ tuiDenies
  ++ lib.concatMap (g: map (p: "Bash(${p})") g.patterns) bashGroups;
}
