# Claude Code's *rules* — the editor guard and the convention hook — are
# configuration, so they are declared here rather than hand-written into the home
# directory. Claude Code reads /etc/claude-code/managed-settings.json ahead of
# ~/.claude/settings.json and wins on conflict, which is what makes this the right
# half of the split: settings.json stays writable for state (theme, dialogs) while
# the rules come from the repo and survive a reinstall.
#
# The instructions themselves (CLAUDE.md) and the convention checker are declared
# in modules/home — they belong to the user, not the system.
#
# The permissions.deny entry covers hosts/*/hardware-configuration.nix. That file is
# generated by nixos-generate-config, and tools.json has said "never hand-edited" all
# along — but prose does not stop tooling: a `deadnix --edit` pass stripped an unused
# argument from it twice within ten minutes. Note what this does and does not do. It
# blocks Claude's file tools; it does not block `sed -i` from a shell, and it does not
# block an editor extension. It narrows the way in, it does not seal the file.
# default.nix and disko.nix beside it are hand-written and must stay editable, hence
# the exact filename rather than the directory.
{
  environment.etc."claude-code/managed-settings.json".source = ../../claude/managed-settings.json;
}
