# Claude Code's *rules* — the editor guard, the deny list and the hooks — are
# configuration, so they are declared here rather than hand-written into the home
# directory. Claude Code reads /etc/claude-code/managed-settings.json ahead of
# ~/.claude/settings.json and wins on conflict, which is what makes this the right
# half of the split: settings.json stays writable for state (theme, dialogs) while
# the rules come from the repo and survive a reinstall.
#
# The instructions themselves (CLAUDE.md) and the convention checker are declared
# in modules/home — they belong to the user, not the system.
#
# The permissions.deny entry covers hosts/*/hardware-configuration.nix. That file is
# generated by nixos-generate-config, and tools.json has said "never hand-edited" all
# along — but prose does not stop tooling: a `deadnix --edit` pass stripped an unused
# argument from it twice within ten minutes. Note what this does and does not do. It
# blocks Claude's file tools; it does not block `sed -i` from a shell, and it does not
# block an editor extension. It narrows the way in, it does not seal the file.
# default.nix and disko.nix beside it are hand-written and must stay editable, hence
# the exact filename rather than the directory.
#
# The rest of permissions.deny generalises that same finding. CLAUDE.md had a dozen
# "never do X" lines, all of them handshakes of exactly the kind the deadnix pass broke.
# The ones listed here are the subset where the command *exists on this machine and
# succeeds at the wrong thing*: jjui/btop/fzf/`zellij attach` and jj's diff-editor forms
# hang a session that has no terminal; `sg` is util-linux's setgid wrapper rather than
# ast-grep; `nh os switch` reaches a sudo prompt nothing can answer. Absent tools are
# deliberately not listed — `command not found` is already the wall for pip, python3,
# node, cargo and wget, and a rule there would duplicate a fact the machine states
# better. Preferences (rg over grep -r, sponge over `> tmp && mv`) stay in prose,
# because they concern cost rather than a call that cannot work.
#
# Two rules are hooks instead of deny entries, because a flat pattern would be wrong
# somewhere. `git commit` is correct in a git-only repo and only destructive in a
# colocated one, so the PreToolUse hook looks for .jj in the working directory and
# denies on that. And `nix flake check` is the pre-commit gate jj cannot host: jj has no
# hook support and bypasses .git/hooks, so the check runs from a PreToolUse hook on
# `jj commit` and `jj git push` and denies the call when it fails. Roughly ten seconds
# on this tree, and it only fires when the working directory is /etc/nixos.
#
# permissions.allow is the other side of the same argument. Sessions here start in auto
# mode, where a classifier reviews shell commands in place of a prompt — so before this
# list, `rg`, `jj log` and `nh os build` each cost a round trip and could be refused, and
# a refusal carried no information because everything was reviewed alike. An allow rule
# resolves before the classifier runs, so the list moves the reading half of the workflow
# off that path and leaves review for calls that change something.
#
# It was derived rather than imagined: `jq` over the Bash calls in ~/.claude/projects,
# split on shell separators and counted by binary. That is also why the list is short.
# What Claude Code already treats as read-only (ls, cat, head, tail, grep, find, wc,
# diff, stat, and git's read-only forms) is deliberately absent for the same reason the
# absent tools are — a rule there would restate a decision already made elsewhere.
#
# Three entries the counts argued for and safety did not. `sed -n` appeared ~700 times,
# but `-n` does not stop sed's `w` command from writing a file. `devenv shell --` was the
# single most common command in the transcripts, and it runs whatever follows it, which
# is exactly the case Claude Code documents as unsafe to allowlist. `awk` can redirect
# inside its own program. All three keep prompting, on purpose.
#
# `fd` and `nix eval` are allowed with their escape hatches denied above: `fd -x/-X` runs
# arbitrary commands and is idiomatic enough to type by accident, and `nix eval
# --write-to` writes a directory. Deny beats allow, so the pair composes. The standard
# applied throughout is "would a normal invocation ever do this by accident", not "is it
# unreachable by someone trying" — rg's `--pre` can run a command too, and is left alone
# because nobody arrives there without meaning to.
#
# Not included: `Bash(* --version)` and `Bash(* --help *)`, which law 6 would otherwise
# want. Auto mode drops leading-wildcard allow rules as broad grants of execution, so
# they would be dead weight here and misleading to read.
#
# One accepted cost: a pattern like `Bash(btop *)` also blocks `btop --version`, which
# law 6 otherwise recommends. Deny beats allow, so no exception can be carved back out,
# and a narrower pattern cannot express "every invocation except the informational
# flags". Versions for these four come from tools.json or `nix eval` instead.
#
# Same caveat as above, one level out: a deny rule matches what Claude's own tools run.
# It does not follow `direnv exec`, `devbox run`, or a script that calls the same
# command a level down. It narrows the way in, it does not seal it.
{
  environment.etc."claude-code/managed-settings.json".source = ../../claude/managed-settings.json;
}
