# Plane, self-hosted: project management, as five pinned containers.
#
# Upstream ships no nixpkgs attribute and no NixOS module — checked 2026-08-30:
# `pkgs.plane` is not an attr, `nix-locate --top-level bin/plane` finds nothing,
# and `options.services.plane` does not exist. Containers are the only
# distribution, so declaring Plane means declaring containers; the alternative
# is `curl … | sh` running upstream's setup.sh, which is law 1 with the serial
# numbers filed off. This header is the whole record of that decision — there was
# a longer evaluation document beside it and it was removed on purpose, so what
# is worth keeping lives here, next to the thing it explains.
#
# ── why containers all the way down, against this repo's own default ─────────
#
# The default here is native services over containers, and it is right in
# general. It loses for this one case because the data tier would exist SOLELY
# to serve Plane, and a Postgres serving exactly one containerised application
# should share that application's version matrix rather than being promoted to a
# machine-wide service. Concretely: upstream tests against postgres 15.7, valkey
# 7.2.11 and rabbitmq 3.13.6 — the pins below — and releases every week or two.
# Substituting NixOS's Postgres major, real Redis for Valkey and a different
# RabbitMQ would build a matrix upstream never runs and leave it to be debugged
# alone. Containerised, an upgrade moves five digests as the set upstream tested
# together, and removal is `git rm` on this file.
#
# The second reason is isolation: a private bridge with one published port on
# loopback replaces the `--network=host` a hybrid arrangement needs to let a
# container reach services on the host.
#
# What this does NOT buy, stated plainly: any Plane at all is a permanent web
# app on the docker daemon that exists here for winboat. That posture change is
# paid by every shape of this, and tools.json's "not an invitation" sentence is
# amended alongside this file rather than left to contradict it.
#
# ── pinning ─────────────────────────────────────────────────────────────────
#
# By digest, never by tag. Tags move; a digest is the thing that stops an
# unattended rebuild quietly changing which Plane runs. Upgrading is therefore a
# deliberate edit here, with the new digests read from the registry:
#
#   curl -s 'https://hub.docker.com/v2/repositories/makeplane/plane-aio-community/tags?page_size=5' \
#     | jq -r '.results[] | "\(.name)  \(.digest)"'
#
# Resolved 2026-08-30. plane-aio v1.4.2 and stable are the same digest.
#
# ONE OF THE FIVE IS NOT LIKE THE OTHERS. `plane-pgdata` was initialised by
# postgres 15.7, and a postgres image only reads a data directory written by its
# own major. Pasting a 16 or 17 digest into `images.postgres` builds clean,
# passes `nix flake check`, restarts the container on switch, and then fails with
# "database files are incompatible with server" — against a volume nothing backs
# up. A postgres major bump is a dump-and-restore, not a digest edit; the four
# others are safe to move on their own.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  # The secret file: root-only, on the encrypted root, never in this repo (law 7
  # — /etc/nixos is public and every nix file is world-readable in the store).
  # It is GENERATED by plane-secrets.service below rather than authored by hand;
  # what follows is the shape it gets, and what to edit if you ever want to point
  # Plane at storage or a database somewhere else.
  #
  # Law 7 forbids the values living in a nix file. It does not forbid the
  # procedure, and this machine already declares that procedure elsewhere:
  # installer.sh generates the LUKS key from /dev/urandom and hashes the user
  # password into this same directory. A hand-typed recipe would have been the
  # one imperative step in an otherwise declared deployment, and the worse half
  # of that is that the recipe would live wherever it was typed instead of here.
  #
  # Four of the five containers read this same file — plane-redis needs nothing
  # and gets nothing. That is a choice made here, NOT upstream's: their compose
  # hands `.env` to plane-db and plane-mq only, and gives plane-minio two
  # explicit variables. An earlier version of this comment claimed the blanket
  # file was upstream's arrangement, and the source says otherwise.
  #
  # It is still the right trade on this machine, for one reason worth stating
  # against its cost. The cost is real, and larger than "the container can see
  # its own environment": every value in this file lands in each container's Env
  # array, which `docker inspect plane-db` prints — and winboat.nix puts this
  # machine's user in the docker group. So the Postgres superuser password, the
  # RabbitMQ password and the MinIO root credentials are readable by any process
  # running as the user, out of a file whose mode 0700 on an encrypted root says
  # they are not. That group is already root-equivalent here, which is why this
  # is a stated cost rather than a hole — but it is a wider readback path than
  # the file's permissions suggest, and it is what a second consumer of this
  # machine would have to be told.
  #
  # The reason it is still worth it: the three value-pairs below have to agree,
  # and one generated file is the only arrangement where they cannot drift —
  # four narrower files would need the same values written four times.
  #
  #   POSTGRES_USER=plane
  #   POSTGRES_DB=plane
  #   POSTGRES_PASSWORD=<a>
  #   DATABASE_URL=postgresql://plane:<a>@plane-db:5432/plane
  #   RABBITMQ_DEFAULT_USER=plane
  #   RABBITMQ_DEFAULT_PASS=<b>
  #   RABBITMQ_DEFAULT_VHOST=plane
  #   AMQP_URL=amqp://plane:<b>@plane-mq:5672/plane
  #   MINIO_ROOT_USER=<c>
  #   MINIO_ROOT_PASSWORD=<d>
  #   AWS_ACCESS_KEY_ID=<c>
  #   AWS_SECRET_ACCESS_KEY=<d>
  #   SECRET_KEY=<openssl rand -hex 32>
  #   LIVE_SERVER_SECRET_KEY=<openssl rand -hex 32>
  #
  # <a> appears twice, <b> twice, and <c>/<d> twice: MinIO's root credentials ARE
  # the application's S3 keys, and THAT part is upstream's arrangement — their
  # compose writes `MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}`. Nothing composes
  # those URLs in nix, because composing them there would mean the password
  # passing through a world-readable store path.
  envFile = "${config.machine.secretsDir}/plane.env";

  network = "plane";

  # Port 80 is written as a literal below, three times, and there is deliberately
  # NO `sitePort` binding to change. It looked like a knob and was a trap: moving
  # it moves the host publish and nothing else, so Plane starts cleanly and is
  # completely broken — SITE_ADDRESS and the container-side port stay at 80, and
  # DOMAIN_NAME=localhost still makes the image derive WEB_URL=http://localhost,
  # so the frontend links to a port nothing serves and CORS rejects the browser's
  # own origin.
  #
  # 80 is forced rather than chosen. The image's start.sh validates DOMAIN_NAME as
  # an FQDN or an IP and then DERIVES the URLs from it, overwriting whatever was
  # passed in:
  #
  #   update_env_value "WEB_URL" "$app_protocol://$DOMAIN_NAME"
  #   update_env_value "CORS_ALLOWED_ORIGINS" "http://$DOMAIN_NAME,https://$DOMAIN_NAME"
  #
  # A port cannot be in DOMAIN_NAME — the colon fails the validator, which is how
  # this was found: `DOMAIN_NAME=localhost:8080` exited 1 with "not a valid FQDN
  # or IP address" and the unit hit its restart limit. And it cannot be left out
  # of the URLs either. Serving at the root is the only arrangement where both are
  # true. Nothing else listens on 80 here (checked: nginx and caddy are off, and
  # `ss -ltn` showed the port free), and the publish is loopback-scoped, so this
  # takes nothing from the host but the name. Moving Plane to another port means
  # putting a reverse proxy in front of it, not editing a number here.

  images = {
    aio = "makeplane/plane-aio-community@sha256:161732a94fee446f87392422994bb7fbcf0b94b9b515fb622b6ea66b5ed5ccea";
    postgres = "postgres@sha256:468d34fefd6338031787c7b8e94078975b3aaf4d66c7ead25c39cd3ba46a15c6";
    valkey = "valkey/valkey@sha256:10328d00120dc14fbc87b2ed61b7677ddbb0d011e705361b4788329a0ec69a93";
    rabbitmq = "rabbitmq@sha256:611107e29cce05c2acd968325d5dcbde7e2fee404970f1ead75fdb22be2821b3";
    # Untagged in upstream's compose, which means `latest`. Pinned to the newest
    # dated release instead — 2025-09-07, and MinIO has published nothing since,
    # so this costs no freshness.
    minio = "minio/minio@sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e";
  };

  # Every container waits on the network and on the secret being written.
  #
  # `wants`, not `requires`, for plane-secrets. It is a oneshot held active only
  # by RemainAfterExit, so a `systemctl stop plane-secrets` — a plausible thing
  # to type while looking at the generation step, since the unit has long
  # finished its work — would propagate through Requires= and tear down a
  # running issue tracker. Wants gets the same pull-in and the same ordering
  # without making a finished oneshot load-bearing at runtime, and the condition
  # below already covers the case it failed. The bridge keeps `requires`,
  # because a container cannot join a network that is not there.
  #
  # ConditionPathExists is what keeps a machine whose plane.env generation
  # failed from crash-looping five units: they are skipped, cleanly, and
  # `systemctl status plane-secrets` is what says why. There is deliberately no
  # activation-time warning (see the end of this file).
  #
  # plane-redis gets this too, though it reads no secret — the comment above
  # says as much. Deliberate: without a secret the other four are down and a
  # lone Valkey serves nobody, so it is simpler for the five to share one
  # lifecycle than to carve out the one exception.
  common = {
    after = [
      "docker-network-plane.service"
      "plane-secrets.service"
    ];
    requires = [ "docker-network-plane.service" ];
    wants = [ "plane-secrets.service" ];
    unitConfig.ConditionPathExists = envFile;
    # nixpkgs gives these units Restart="on-failure" with no RestartSec, so the
    # default 100ms applies and systemd's default limit is five starts in ten
    # seconds. `dependsOn` orders the app after the database but says nothing
    # about READINESS — the unit counts as started the moment `docker run` execs,
    # not when Postgres accepts connections — so a cold boot where the app
    # container exits fast on a refused connection can burn the whole budget in
    # under a second and leave it permanently failed, needing a manual
    # `systemctl reset-failed`. That exact state was reached once during
    # development, for a different reason (see the DOMAIN_NAME note in the
    # header), which is how the shape of it is known. Ten seconds between
    # attempts turns five tries in one second into five tries in a minute.
    serviceConfig.RestartSec = "10s";
  };
  # The container set, bound here rather than written inline below, so the
  # systemd ordering can be DERIVED from it by name. Inline, the two lists
  # could only be kept in step by hand or by matching on a name prefix, and
  # both of those drift: rename plane-mq to rabbitmq, or add a sixth container
  # called caddy, and a prefix filter silently drops its ordering while an
  # unrelated `planetscale-proxy` would silently inherit it.
  planeContainers = {
    # ── data tier: upstream's own images, at upstream's own versions ────────
    # Named docker volumes rather than bind mounts. Two reasons, and the
    # trade-off is real: the postgres image insists on owning its data
    # directory, which a bind mount turns into a uid-matching exercise; and
    # /var/lib/docker is ALREADY persisted (impermanence.nix, for winboat), so
    # the data survives a reboot with nothing further declared.
    #
    # The cost, unanswered: the data lives inside the docker tree rather than
    # somewhere obvious, and NOTHING BACKS IT UP. A reboot is survived; a wiped
    # /var/lib/docker, a `docker volume prune`, or dropping the impermanence
    # entry is not. An issue tracker that cannot be restored is worse than no
    # issue tracker, and closing that gap means a pg_dump timer writing
    # somewhere under /persistent — not written yet, and this comment is the
    # only thing recording that it is missing.
    plane-db = {
      image = images.postgres;
      environmentFiles = [ envFile ];
      environment.PGDATA = "/var/lib/postgresql/data";
      # Upstream's own flag. Plane opens a connection per worker and the
      # default 100 is not enough for the aio bundle.
      cmd = [
        "postgres"
        "-c"
        "max_connections=1000"
      ];
      volumes = [ "plane-pgdata:/var/lib/postgresql/data" ];
      networks = [ network ];
    };

    plane-redis = {
      image = images.valkey;
      volumes = [ "plane-redisdata:/data" ];
      networks = [ network ];
    };

    plane-mq = {
      image = images.rabbitmq;
      environmentFiles = [ envFile ];
      volumes = [ "plane-rabbitmq:/var/lib/rabbitmq" ];
      networks = [ network ];
    };

    plane-minio = {
      image = images.minio;
      environmentFiles = [ envFile ];
      cmd = [
        "server"
        "/export"
        "--console-address"
        ":9090"
      ];
      volumes = [ "plane-uploads:/export" ];
      networks = [ network ];
      # Published, unlike the rest of the data tier, and the reason is the one
      # thing about this deployment that is genuinely awkward. Plane hands the
      # BROWSER presigned URLs built from AWS_S3_ENDPOINT_URL — see
      # apps/api/plane/settings/storage.py, where `USE_MINIO=1` would sign
      # against the request's own host instead, and the aio image's start.sh
      # hard-writes USE_MINIO=0. So the endpoint has to resolve on both sides:
      # inside the bridge, where docker's DNS answers for `plane-minio`, and in
      # the browser, where networking.hosts below points the same name at
      # loopback. One name, one signature host, both directions.
      #
      # The alternative was replacing the image's Caddyfile: upstream's FULL
      # compose proxies `/{$BUCKET_NAME}/*` to plane-minio and the aio's
      # Caddyfile.aio.ce simply has no such route (both fetched and compared).
      # That means overriding a file inside the image and forcing USE_MINIO
      # back to 1 against a start.sh that rewrites it — fighting the image, and
      # breaking on any upgrade that moves the file.
      ports = [ "127.0.0.1:9000:9000" ];
    };

    # ── app tier: eight of Plane's services in one supervised container ─────
    # web, space, admin, api, live, worker, beat and a Caddy proxy. The only
    # container that publishes anything, and it publishes to loopback.
    plane = {
      image = images.aio;
      environmentFiles = [ envFile ];
      environment = {
        # Not secrets, so they are declared where they can be read — and NOT
        # overridable from plane.env, which is the opposite of what an earlier
        # version of this comment claimed. `environmentFiles` becomes docker's
        # `--env-file` (nixpkgs oci-containers.nix) and `--env` wins over it,
        # so every name below is fixed here and editing it in the secret file
        # silently does nothing. Anything that should be an operator's choice
        # therefore belongs in plane.env and NOT in this attrset: DATABASE_URL
        # and AMQP_URL are exactly that, and are absent here on purpose.
        SITE_ADDRESS = ":80";
        # A bare hostname, because the image validates this and then builds
        # WEB_URL and CORS_ALLOWED_ORIGINS out of it. Setting those two here
        # would be writing values the container overwrites on every start, so
        # they are deliberately absent: DOMAIN_NAME is the only knob, and the
        # port-80 comment above is why it can carry no port.
        DOMAIN_NAME = "localhost";
        # By container name: docker's embedded DNS resolves these on a
        # user-defined bridge, which is the whole reason for the network. The
        # storage endpoint is also the one the browser is handed, which is why
        # plane-minio is published and aliased on the host — see its own
        # comment, and networking.hosts below.
        REDIS_URL = "redis://plane-redis:6379";
        AWS_S3_ENDPOINT_URL = "http://plane-minio:9000";
        AWS_S3_BUCKET_NAME = "plane-uploads";
        AWS_REGION = "us-east-1";
      };
      # The bucket needs no oneshot: Plane creates it itself on API startup
      # (apps/api/plane/db/management/commands/create_bucket.py, called from
      # bin/docker-entrypoint-api.sh). Verified in upstream's tree rather than
      # assumed — their compose has no createbuckets service either.
      dependsOn = [
        "plane-db"
        "plane-redis"
        "plane-mq"
        "plane-minio"
      ];
      ports = [ "127.0.0.1:80:80" ];
      networks = [ network ];
    };
  };

in
{
  virtualisation.oci-containers = {
    # The option's default is podman, which is not installed here and is denied
    # outright in agent-denies.nix. Docker is already running for winboat, so
    # this reuses that daemon rather than putting a second runtime on the machine
    # for one application.
    # mkDefault, so a host that wants podman can say so instead of hitting a
    # conflicting-definition error: `backend` is an enum merged with
    # mergeEqualOption, and two plain definitions that disagree fail to evaluate
    # with no resolution but editing one of them.
    backend = lib.mkDefault "docker";

    containers = planeContainers;
  };

  # The one thing oci-containers will not do. Its `networks` option only emits
  # `--network=` flags — the module creates no networks (read its source: no
  # network creation in its 648 lines), so the bridge is a oneshot. This is the
  # same unit compose2nix generates for the same reason.
  # The other half of the storage fix, and the part that looks strangest: the
  # host resolves a CONTAINER's name. Plane signs presigned URLs against
  # AWS_S3_ENDPOINT_URL and hands them to the browser, so that one name has to
  # answer in two places — docker's embedded DNS inside the bridge, and this
  # entry outside it. Same host in the URL means the same host in the signature,
  # which is what makes MinIO accept the request from either side.
  #
  # It is only reasonable because this deployment is loopback-only by
  # construction: the browser is always on this machine. A Plane reachable from
  # the LAN would need upstream's arrangement instead — its proxy routing
  # /{bucket}/* at MinIO, with USE_MINIO=1 — which the aio image cannot do
  # without replacing a file inside it.
  networking.hosts."127.0.0.1" = [ "plane-minio" ];

  # One `systemd.services` attribute, not two: the container units get the shared
  # ordering, and the bridge and secret units are spliced in beside them.
  #
  # The names are DERIVED from `planeContainers` itself — the same value that
  # becomes the container set — so the two cannot disagree in either direction.
  # Hand-listing them meant a new or renamed container silently lost its
  # `After=`/`Wants=` on the bridge and the secret, starting before the network
  # existed or with no credentials and saying nothing. Matching on a `plane`
  # name prefix, which this replaced, had both failure modes at once: rename
  # plane-mq to rabbitmq and it drops out, add an unrelated planetscale-proxy
  # and it is silently adopted.
  #
  # The unit NAME comes from each container's own `serviceName`, not from
  # "docker-" spelled out here. nixpkgs defaults that to "${backend}-${name}",
  # so a hardcoded prefix quietly detaches everything below the moment the
  # backend is not docker: the real units come out as podman-plane-* with no
  # ordering and no ConditionPathExists, and five orphan docker-plane-* units
  # appear carrying the ordering and no ExecStart. Reading serviceName follows
  # the backend and any per-container override with it.
  systemd.services =
    lib.genAttrs (map (n: config.virtualisation.oci-containers.containers.${n}.serviceName) (
      lib.attrNames planeContainers
    )) (_: common)
    // {
      # Law 7 keeps the VALUES out of this repo; it does not make generating
      # them a manual step. This is the declared procedure, and it is the same
      # shape installer.sh uses for the LUKS key and the password hash.
      #
      # Three properties it has to have, in order of how badly each would hurt:
      #
      #   never overwrites  POSTGRES_PASSWORD is read by the postgres image on
      #                     FIRST INIT only. Regenerating it after the database
      #                     exists locks Plane out of its own data, with no way
      #                     back short of dropping the volume. Hence the `-s`
      #                     guard, and hence no rotation logic here at all.
      #   atomic            written to a temp file and renamed, so an
      #                     interrupted run cannot leave a half-written file
      #                     that the `-s` guard would then treat as done. The
      #                     "never > tmp && mv" rule in CLAUDE.md is about
      #                     editing a file in place, where the redirect
      #                     truncates the reader's own input; nothing is read
      #                     here, and atomic creation is the opposite case.
      #   consistent        three values appear twice each — the database
      #                     password inside DATABASE_URL, the rabbit password
      #                     inside AMQP_URL, and MinIO's root credentials as the
      #                     application's S3 keys. Generating them in one place
      #                     is what stops those pairs drifting apart.
      #
      # The file is ordinary text afterwards, and nothing here rewrites it. What
      # editing it can actually change is narrower than it looks: DATABASE_URL
      # and AMQP_URL are file-only, so pointing Plane at an external Postgres or
      # broker works. The storage settings do NOT — AWS_S3_ENDPOINT_URL,
      # AWS_S3_BUCKET_NAME and AWS_REGION are passed with `--env` in the
      # container block above, and docker's `--env` beats `--env-file`. Moving to
      # a real S3 means editing that attrset, not this file.
      plane-secrets = {
        description = "generate Plane's secret env file, once, if it is absent";
        wantedBy = [ "multi-user.target" ];
        # The directory is on the encrypted root, which is a mount rather than
        # part of /. Without this the unit can run before it is there and write
        # the secret into the ephemeral tree, where it vanishes at reboot and
        # leaves the database with a password nothing knows.
        unitConfig.RequiresMountsFor = config.machine.secretsDir;
        path = [ pkgs.coreutils ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          UMask = "0077";
        };
        # No `install -d` on the secrets directory: impermanence.nix already
        # declares `d ${config.machine.secretsDir} 0700 root root` as a tmpfiles
        # rule, and systemd-tmpfiles-setup runs in sysinit.target, long before a
        # multi-user.target oneshot. Creating it here again would never have work
        # to do and would put the 0700 in a second place, where a later change to
        # one would silently lose to the other.
        script = ''
          # pipefail matters more here than anywhere else in this repo. `rand`
          # is a pipeline, and a pipeline's status is its LAST command's — so a
          # failed or short `head` on /dev/urandom yields an empty string, `tr`
          # exits 0, `set -e` sees nothing, and the heredoc happily writes
          # POSTGRES_PASSWORD= and a DATABASE_URL with no password in it. The
          # file is then non-empty, the `-s` guard below treats it as done
          # forever, and the blank password is baked into the volume on first
          # init. The length check after each call is the second half of that:
          # pipefail catches a failure, the check catches a short read.
          set -euo pipefail
          if [ -s ${lib.escapeShellArg envFile} ]; then
            exit 0
          fi

          # coreutils only — there is no openssl on PATH here — and hex rather
          # than base64, because two of these values are embedded in URLs where
          # a "/", "+" or "@" would break the parse.
          rand() {
            local out
            out=$(head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n')
            # Two hex characters per byte, or the read was short.
            if [ "''${#out}" -ne "$(( $1 * 2 ))" ]; then
              echo "rand $1 produced ''${#out} characters, not $(( $1 * 2 ))" >&2
              return 1
            fi
            printf '%s' "$out"
          }
          db=$(rand 24)
          mq=$(rand 24)
          ak=$(rand 12)
          sk=$(rand 24)
          secret=$(rand 32)
          live=$(rand 32)

          # Removed first and on any exit: an interrupted run would otherwise
          # leave a full set of credentials that were never adopted sitting in
          # the one directory whose contents are supposed to BE the secrets, and
          # nothing would ever clean it up.
          tmp=${lib.escapeShellArg envFile}.tmp
          trap 'rm -f "$tmp"' EXIT
          rm -f "$tmp"
          cat > "$tmp" <<EOF
          POSTGRES_USER=plane
          POSTGRES_DB=plane
          POSTGRES_PASSWORD=$db
          DATABASE_URL=postgresql://plane:$db@plane-db:5432/plane
          RABBITMQ_DEFAULT_USER=plane
          RABBITMQ_DEFAULT_PASS=$mq
          RABBITMQ_DEFAULT_VHOST=plane
          AMQP_URL=amqp://plane:$mq@plane-mq:5672/plane
          MINIO_ROOT_USER=$ak
          MINIO_ROOT_PASSWORD=$sk
          AWS_ACCESS_KEY_ID=$ak
          AWS_SECRET_ACCESS_KEY=$sk
          SECRET_KEY=$secret
          LIVE_SERVER_SECRET_KEY=$live
          EOF
          # No chmod: UMask=0077 above already creates it 0600, so a chmod here
          # would be closing a window that never opened. The rename is what makes
          # the file appear complete or not at all.
          mv "$tmp" ${lib.escapeShellArg envFile}
        '';
      };

      docker-network-plane = {
        description = "the private bridge Plane's containers talk over";
        path = [ config.virtualisation.docker.package ];
        after = [ "docker.service" ];
        requires = [ "docker.service" ];
        wantedBy = [ "multi-user.target" ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        # Idempotent: runs on every boot, does nothing on the second one. No
        # ExecStop removing the network — tearing it down while containers are
        # still attached fails, and a network left behind costs nothing.
        script = ''
          docker network inspect ${network} >/dev/null 2>&1 || docker network create ${network}
        '';
      };
    };

  # The one claim in this file that a comment cannot keep true. Plane's five
  # volumes live in the docker tree, nothing backs them up, and their entire
  # survival across a reboot rests on impermanence.nix persisting
  # /var/lib/docker — an entry whose own comment was about winboat until Plane
  # arrived. A prose warning there is a handshake; this is the wall. Delete that
  # line while Plane is declared and the build fails instead of the tracker
  # disappearing at the next boot.
  #
  # `d.directory or d` is defensive, not required: evaluated, every entry in that
  # list comes back as a submodule with a `.directory` string, so the fallback
  # branch is never taken today. An earlier version of this comment asserted the
  # opposite — that bare strings and attrsets both appear — which is wrong, and
  # is corrected here rather than left to send a reader looking for a mixed-type
  # list. The `or d` stays because the option ACCEPTS bare strings and a future
  # impermanence could stop normalising them, and a wrong assertion here is worse
  # than a redundant branch.
  #
  # Watched going red on purpose (CLAUDE.md): commenting out "/var/lib/docker" in
  # impermanence.nix made `nh os build` fail with this message, and restoring it
  # made the build clean again.
  assertions = [
    {
      assertion = lib.any (
        d: (d.directory or d) == "/var/lib/docker"
      ) config.environment.persistence."/persistent/system".directories;
      message = ''
        modules/nixos/plane.nix declares four docker volumes (plane-pgdata,
        plane-redisdata, plane-rabbitmq, plane-uploads) that hold the whole of
        Plane's data, and /var/lib/docker is no longer in
        environment.persistence."/persistent/system".directories.

        Impermanence wipes everything undeclared, so the next boot would take
        Plane's database with it, and nothing backs it up. Either restore that
        entry in modules/nixos/impermanence.nix, or remove plane.nix from
        modules/nixos/default.nix if Plane is meant to be gone.
      '';
    }
    {
      # The rest of this module follows the backend wherever it goes — unit names
      # come from serviceName, and the containers themselves are backend-agnostic
      # — but ONE piece is not: docker-network-plane runs `docker network create`
      # with the docker CLI. Under podman the containers would ask to join a
      # network that only exists in docker's store, and start with no bridge.
      #
      # So the backend stays mkDefault (a host may have a reason) and this says
      # what such a host would have to fix, instead of the module half-working.
      assertion = config.virtualisation.oci-containers.backend == "docker";
      message = ''
        modules/nixos/plane.nix assumes the docker backend, but
        virtualisation.oci-containers.backend is
        "${config.virtualisation.oci-containers.backend}".

        Its bridge unit (docker-network-plane) creates the network with the
        docker CLI, so under another backend the containers would join a network
        that does not exist there. Point that unit at the chosen backend's CLI
        before switching, or set the backend back to "docker".
      '';
    }
  ];

  # No activation-time warning about a missing plane.env. There was one, in the
  # shape users.nix uses for the password hash, and plane-secrets makes it both
  # obsolete and wrong: activation scripts run BEFORE systemd starts the units,
  # so on the first switch it would fire every time and then be false a second
  # later. A warning that cries wolf on a working machine is worse than no
  # warning — if generation fails, `plane-secrets.service` fails, the five
  # containers that require it never start, and systemctl says exactly that.
}
